### TEST ROUTES HERE

GET http://localhost:9000/users

### + or %20 --> specify 'space'

GET http://localhost:9000/users?username=Henrique+Pitta


### User doesn't exist

GET http://localhost:9000/users?username=Henry+Smith

###

POST http://localhost:9000/users
Content-Type: application/json

{
    "username": "Henrique Pitta",
    "profilepic": "empty",
    "followers": [],
    "following": []
}

###

POST http://localhost:9000/users
Content-Type: application/json

{
    "username": "Evelise Pitta",
    "profilepic": "empty",
    "followers": [],
    "following": ["Henrique Pitta"],
    "playlists": ["Rescue Church"]
}

###

POST http://localhost:9000/users
Content-Type: application/json

{
    "username": "Henrique Pitta"
}

###

DELETE http://localhost:9000/users

###

DELETE http://localhost:9000/playlists

###

DELETE http://localhost:9000/songs






### Album Reference TEST - DO THIS

GET http://localhost:9000/playlists

###

POST http://localhost:9000/users
Content-Type: application/json

{
    "username": "Fred Again..",
    "profilepic": "empty"
}

###

POST http://localhost:9000/playlists
Content-Type: application/json

{
    "title": "ten days",
    "owner": "Fred Again.."
}

###

POST http://localhost:9000/playlists
Content-Type: application/json

{
    "title": "Rapsito",
    "owner": "Henrique Pitta",
    "playlist": true
}

### Song Reference TEST - DO THIS

GET http://localhost:9000/songs

###

DELETE http://localhost:9000/songs

###

POST http://localhost:9000/songs
Content-Type: application/json

{
    "title": "where will i be",
    "artist": "Fred Again..",
    "album": "ten days"
}

###
# "title": "adore u",
# "title": "fear less",
# "title": "where will i be",